In [ ]:
import pandas as pd
import numpy as np

#Pandas

- Pandas is a python library used for working with data sets.
- It has functions for analyzing, cleaning, exploring, and manipulating data.
- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.
- Pandas allows us to analyze big data and make conclusions based on statistical theories.
- Pandas can clean messy data sets, and make them readable and relevant.
- Relevant data is very important in data science.

## Series
- A Pandas Series is like a column in a table.
- It is a one-dimensional array holding data of any type.

In [ ]:
# Create a simple panda series from a list:
import pandas as pd
a = [1,7,2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

## Labels
(index number)

In [ ]:
print(myvar[0])

1

## Create Labels
- With the index arguments,you can name your own labels.

In [ ]:
# Crate your own labels:
import pandas as pd
a =[1,7,2]
myvar = pd.Series(a,index =["x","y","z"])
print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
# Return the value of"y":
print(myvar["y"])

7

## Key/Value Objects as Series
- You can also use a key/value object,like a dicionary,when creating a series.

In [ ]:
# Create a simple pandas seies from a dictionary:
import pandas as pd
calories ={"day1":420,"day2":380,"day3":390}
myvar =pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [ ]:
# Create a series only data from"day1" and "day2":
import pandas as pd
calories = pd.Series(calories,index =["day1","day2"])
print(myvar)

day1    420
day2    380
day3    390
dtype: int64

# DataFrames
- Data sets in Pandas are usually multi-dimensional tables, called DataFrames.
- Series is like a column, a DataFrame is the whole table.

In [ ]:
# Create a DataFrame from two series:
import pandas as pd
data = {"calories":[420,380,390],
        "duration":[50,40,45]}
myvar =pd.DataFrame(data)
myvar

   calories  duration
0       420        50
1       380        40
2       390        45

## Locate Row
- Pandas use the loc attribute to return one or more specified row(s)

In [ ]:
# return row 0:
# refer to the row index
print(myvar.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [ ]:
# return row 0 and 1:
# use a list of indexes:
myvar.loc[[0,1]]

   calories  duration
0       420        50
1       380        40

## Named Indexes
- With the index argument, you can name your own indexes.

In [ ]:
# Add a list of names to give each row a name:
import pandas as pd
data ={"calories":[420,380,390],
       "duration":[50,40,45]}
df = pd.DataFrame(data,index = ["day1","day2","day3"])
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

## Locate Names Indexes
- Use the named index in the loc attribute to return the specified row(s)

In [ ]:
# Return "day2":
df.loc["day2"]

calories    380
duration     40
Name: day2, dtype: int64

## Load Files Into a DataFrame
- download data/upload/copy path/paste

In [ ]:
data =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (1).csv")
data

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows:

In [ ]:
# print the DataFrame without the to_string() method
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (1).csv")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

## max_rows
-The number of rows returned is defined in Pandas option settings.

- You can check your system's maximum rows with the pd.options.display.max_rows statement.

In [ ]:
# Check the pandas as ps
print(pd.options.display.max_rows)

60

In [ ]:
# increase the maximum number of rows to display the entire Dataframe:
import pandas as pd
pd.options.display.max_rows =999
df =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (1).csv")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

# Pandas Reads JSON
## read JSON
- Big data sets are often stored, or extracted as JSON.

- JSON is plain text, but has the format of an object, and is well known in the world of programming, including Pandas.

In [ ]:
import pandas as pd
df = pd.read_json("/content/drive/MyDrive/Colab Notebooks/dataset/data.json")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

## Dictionary as JSON

In [ ]:
#Load a python Dictionary into a DataFrame:
import pandas as pd
data ={
    "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}
df = pd.DataFrame(data)
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

# Pandas - Analyzing DataFrames
## Viewing the Data
- One of the most used method for getting a quick overview of the DataFrame, is the head() method.

- The head() method returns the headers and a specified number of rows, starting from the top.

In [ ]:
# Get a quick overview by printing the first 10 rows of the DataFrame:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (1).csv")
df.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [ ]:
# print the first 5 rows of the DataFrame:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (1).csv")
df.head() # ullil onnum kodthillel first 5 rows print aayi varum

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

- There is also a tail() method for viewing the last rows of the DataFrame.

- The tail() method returns the headers and a specified number of rows, starting from the bottom.

In [ ]:
# print the last 5 rows of the DataFrame:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

# Info Abiut the Data
- The DataFrames object has a method called info(), that gives you more information about the data set

In [ ]:
# print information about the data:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

# Pandas - Cleaning Data
## Data Cleaning
Data cleaning means fixing bad data in your data set.

Bad data could be:

- Empty cells
- Data in wrong format
- Wrong data
- Duplicates

## Remove Rows

If you want to change the original DataFrame, use the inplace = True argument:

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset_with_nulls.csv")
df   #null data

   ID     Name   Age            Email  Country   Salary
0   1    Alice  25.0  alice@email.com      USA  50000.0
1   2      Bob   NaN    bob@email.com   Canada  54000.0
2   3  Charlie  30.0              NaN       UK      NaN
3   4    Diana  28.0  diana@email.com      NaN  58000.0
4   5    Ethan   NaN  ethan@email.com      USA  62000.0
5   6      NaN  40.0              NaN  Germany      NaN
6   7    Grace  22.0  grace@email.com      NaN  47000.0
7   8    Henry   NaN  henry@email.com   France  51000.0

In [ ]:
new_df = df.dropna()
new_df # removing the null data row

   ID   Name   Age            Email Country   Salary
0   1  Alice  25.0  alice@email.com     USA  50000.0

In [ ]:
df

   ID     Name   Age            Email  Country   Salary
0   1    Alice  25.0  alice@email.com      USA  50000.0
1   2      Bob   NaN    bob@email.com   Canada  54000.0
2   3  Charlie  30.0              NaN       UK      NaN
3   4    Diana  28.0  diana@email.com      NaN  58000.0
4   5    Ethan   NaN  ethan@email.com      USA  62000.0
5   6      NaN  40.0              NaN  Germany      NaN
6   7    Grace  22.0  grace@email.com      NaN  47000.0
7   8    Henry   NaN  henry@email.com   France  51000.0

In [ ]:
df.dropna(inplace = True)
df # remove all the null data row

   ID   Name   Age            Email Country   Salary
0   1  Alice  25.0  alice@email.com     USA  50000.0

## Replace empty values
- The **fillna()** method allows us to replace empty cells with a value:

In [ ]:
import pandas as pd
df =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset_with_nulls.csv")
df

   ID     Name   Age            Email  Country   Salary
0   1    Alice  25.0  alice@email.com      USA  50000.0
1   2      Bob   NaN    bob@email.com   Canada  54000.0
2   3  Charlie  30.0              NaN       UK      NaN
3   4    Diana  28.0  diana@email.com      NaN  58000.0
4   5    Ethan   NaN  ethan@email.com      USA  62000.0
5   6      NaN  40.0              NaN  Germany      NaN
6   7    Grace  22.0  grace@email.com      NaN  47000.0
7   8    Henry   NaN  henry@email.com   France  51000.0

In [ ]:
# Replace NULL values with the number 130:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset_with_nulls.csv")
df.fillna(130,inplace = True)
df

   ID     Name    Age            Email  Country   Salary
0   1    Alice   25.0  alice@email.com      USA  50000.0
1   2      Bob  130.0    bob@email.com   Canada  54000.0
2   3  Charlie   30.0              130       UK    130.0
3   4    Diana   28.0  diana@email.com      130  58000.0
4   5    Ethan  130.0  ethan@email.com      USA  62000.0
5   6      130   40.0              130  Germany    130.0
6   7    Grace   22.0  grace@email.com      130  47000.0
7   8    Henry  130.0  henry@email.com   France  51000.0

## Replace only for Specified coloumns
- To only replace empty values for one column, specify the column name for the DataFrame:

In [ ]:
# Replace NULL values in the "Calories" coloumns with the number 130:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df.fillna({"Calories":130},inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Replacing Using Mean,Median,or Mode
- Pandas uses the **mean()** **median()** and **mode()** methods to calculate the respective values for a specified column:

### MEAN

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")

In [ ]:
df.fillna({"Calories":df['Calories'].mean()},inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

### MEDIAN

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")

In [ ]:
# Calculate the MEDIAN,and replace any empty values with it:
df.fillna({"Calories":df['Calories'].median()},inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     291.2
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     291.2
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## MODE

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")

In [ ]:
mode_cal = df['Calories'].mode()
mode_cal

0    300.0
Name: Calories, dtype: float64

In [ ]:
#Calculate the MODE,and replace any empty values with it:
df.fillna({"Calories":mode_cal[0]},inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     300.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Pandas - Cleaning Data of Wrong Format
### Data of Wrong Format
### Convert into a correct format

- Pandas has a to_datetime() method for this

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df["Date"]= pd.to_datetime(df["Date"],format = "mixed")
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")

In [ ]:
df.dropna(subset=["Date"],inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# Replacing Values

In [ ]:
# set "Duration" = 45 in  rpow 7:
df.loc[7,"Duration"] = 45 # value mataan with index number
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
# Loop through all values in the "Duration" column:
# If the value is higher than 120,set it to 120:

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")
for x in df.index:
  if df.loc[x,"Duration"]>120:
    df.loc[x,"Duration"]=120
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        120  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Removing Rows

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/calories.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
# Delete rows where "Duration" is higher than 120:
for x in df.index:
  if df.loc[x,"Duration"]>120:
    df.drop(x,inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Discovering Duplicates

- To discover duplicates, we can use the duplicated() method.

- The duplicated() method returns a Boolean values for each row:

In [ ]:
#  Returns True for every row that is duplicate,otherwise False:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [ ]:
print(df.duplicated().sum()) # duplicate count

1

In [ ]:
# Remove all duplicates:
df.drop_duplicates(inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
print(df.duplicated().sum())

0

# Pandas - Data Correlations
## Finding Relationships

- A great aspect of the Pandas module is the corr() method.

- The corr() method calculates the relationship between each column in your data set.

In [ ]:
df.corr(numeric_only=True)

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000  0.004410  0.049959 -0.114169
Pulse     0.004410  1.000000  0.276583  0.513186
Maxpulse  0.049959  0.276583  1.000000  0.357460
Calories -0.114169  0.513186  0.357460  1.000000

# Using Converters
- using converters to convert data using conditions

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (2).csv")
df

    name                age occupation
0   john                 23   Engineer
1  alice                 30     doctor
2   ammu  not available age    teacher

In [ ]:
# Convert occupation of doctor to teacher:
def convert(occupation):
  if occupation=="doctor":
    return"teacher"
  else:
    return occupation


data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/data (2).csv",converters={"occupation":convert})
print(data)

    name                age occupation
0   john                 23   Engineer
1  alice                 30    teacher
2   ammu  not available age    teacher

## Write to excel

In [ ]:

data.to_excel('surumi.xlsx')

## Write two data frames in a single excel file

In [ ]:
# Using write ExcelWriter() method
import pandas as pd
# Example DataFrames
data1 = pd.DataFrame({
    "Name": ["john","Alice"],
    "Age": [23,30]
})
data2 = pd.DataFrame({
    "product": ["pen","Notebook"],
    "Price": [10,50]
})
with pd.ExcelWriter("surumi2.xlsx")as wr:
  data1.to_excel(wr,sheet_name="sheet1")
  data2.to_excel(wr,sheet_name="sheet2")

# Group-by
- Group by is the operation in pandas that create groups of rows  by a column or set of columns
- Group by creates sub dataframes,that means it's actually split the main dataframe into sub dataframes based on a single column value or combination of multiple column value
- groupby() is the method used to do this ,We can pass a single column name or a list of column names as the argument of this method

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/airlines_500_rows.csv")
df

,Airline,IATA_Code,Hub_City,Fleet_Size,Destinations,Founded_Year,Alliance,Ownership,Avg_Ticket_Price (INR)
0,SpiceJet,SG,Hyderabad,231,18,1989,OneWorld,Government,19076
1,Air India,G8,Bangalore,181,70,1987,SkyTeam,Government,13419
2,Air India,G8,Bangalore,55,86,1970,NaN,Private,14515
3,Air India,UK,Chennai,66,35,2009,SkyTeam,Government,18720
4,Go First,6E,Mumbai,205,98,1943,NaN,Government,3110
...,...,...,...,...,...,...,...,...,...
495,Akasa Air,SG,Mumbai,183,47,1992,Star Alliance,Private,3364
496,Air India,G8,Bangalore,236,75,1984,SkyTeam,Private,3424
497,Akasa Air,UK,Hyderabad,152,40,2018,NaN,Private,24423
498,SpiceJet,UK,Kolkata,60,87,1969,SkyTeam,Private,4896
499,Go First,UK,Chennai,44,110,2012,OneWorld,Private,10822

In [ ]:
df.groupby("Airline")["Avg_Ticket_Price (INR)"].max()

Airline
Air India    24822
Akasa Air    24843
Go First     24917
IndiGo       24728
SpiceJet     24773
Vistara      24817
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
df.groupby("Airline")["Avg_Ticket_Price (INR)"].min()

Airline
Air India    2403
Akasa Air    2105
Go First     2643
IndiGo       2003
SpiceJet     2272
Vistara      2065
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
df.groupby("Hub_City")["Avg_Ticket_Price (INR)"].min()

Hub_City
Bangalore    2284
Chennai      2598
Delhi        2003
Hyderabad    2105
Kolkata      2380
Mumbai       2065
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
df.groupby("Hub_City")["Avg_Ticket_Price (INR)"].max()

Hub_City
Bangalore    24166
Chennai      24817
Delhi        24822
Hyderabad    24843
Kolkata      24917
Mumbai       24625
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
result=df.groupby(["Hub_City","Airline"])

In [ ]:
result.get_group(("Delhi","IndiGo"))["Avg_Ticket_Price (INR)"].min()

2003

In [ ]:
df.groupby("Alliance")["Avg_Ticket_Price (INR)"].max()

Alliance
OneWorld         24843
SkyTeam          24817
Star Alliance    24817
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
df.groupby("Alliance")["Avg_Ticket_Price (INR)"].min()

Alliance
OneWorld         2003
SkyTeam          2403
Star Alliance    2701
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
df.groupby("Ownership")["Avg_Ticket_Price (INR)"].max()

Ownership
Government    24917
Private       24822
Name: Avg_Ticket_Price (INR), dtype: int64

In [ ]:
df.groupby("Ownership")["Avg_Ticket_Price (INR)"].min()

Ownership
Government    2003
Private       2065
Name: Avg_Ticket_Price (INR), dtype: int64

# Concat....
- concat() function is used to concatenate two or more DataFrames
- Concat can do both vertically( axis=0) as well as horizontal (axis=1)

In [ ]:
tcs={'id':[101,102,103,104],
'name':['Mithun','Dipin','jose','Rahul'],
 'Age':[25,26,27,29]}
wipro={'id':[101,102,103,104],
'Name':['dev','sreenath','sreerag','shafeel'],
'Age':[24,24,27,26]}
tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)
tcs_emp

    id    name  Age
0  101  Mithun   25
1  102   Dipin   26
2  103    jose   27
3  104   Rahul   29

In [ ]:
wipro_emp

    id      Name  Age
0  101       dev   24
1  102  sreenath   24
2  103   sreerag   27
3  104   shafeel   26

In [ ]:
pd.concat([tcs_emp,wipro_emp])

    id    name  Age      Name
0  101  Mithun   25       NaN
1  102   Dipin   26       NaN
2  103    jose   27       NaN
3  104   Rahul   29       NaN
0  101     NaN   24       dev
1  102     NaN   24  sreenath
2  103     NaN   27   sreerag
3  104     NaN   26   shafeel

## ignore index
Ignore index —> TO get common index after concatenation

In [ ]:
pd.concat([tcs_emp,wipro_emp],ignore_index=True)

    id    name  Age      Name
0  101  Mithun   25       NaN
1  102   Dipin   26       NaN
2  103    jose   27       NaN
3  104   Rahul   29       NaN
4  101     NaN   24       dev
5  102     NaN   24  sreenath
6  103     NaN   27   sreerag
7  104     NaN   26   shafeel

In [ ]:
data=pd.concat([tcs_emp,wipro_emp],keys=["TCS","WIPRO"])
data

          id    name  Age      Name
TCS   0  101  Mithun   25       NaN
      1  102   Dipin   26       NaN
      2  103    jose   27       NaN
      3  104   Rahul   29       NaN
WIPRO 0  101     NaN   24       dev
      1  102     NaN   24  sreenath
      2  103     NaN   27   sreerag
      3  104     NaN   26   shafeel

In [ ]:
data=pd.concat([tcs_emp,wipro_emp],axis=1)
data

    id    name  Age   id      Name  Age
0  101  Mithun   25  101       dev   24
1  102   Dipin   26  102  sreenath   24
2  103    jose   27  103   sreerag   27
3  104   Rahul   29  104   shafeel   26

In [ ]:
salary=pd.Series([65000,75000,15000,25000],name='salary')
salary

0    65000
1    75000
2    15000
3    25000
Name: salary, dtype: int64

In [ ]:
pd.concat([tcs_emp,salary],axis=1)

    id    name  Age  salary
0  101  Mithun   25   65000
1  102   Dipin   26   75000
2  103    jose   27   15000
3  104   Rahul   29   25000

# Merge

In [ ]:
tcs={'id':[101,102,103,106],
      'name':['Mithun','Dipin','jose','maneesh'],
      'age':[25,26,27,29]}
wipro={'id':[101,102,103,105],
      'name':['dev','sreenath','sreerag','varun'],
      'salary':[25000,34000,37000,20000]}
tcs_emp=pd.DataFrame(tcs)
wipro_emp=pd.DataFrame(wipro)

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id')

    id  name_x  age    name_y  salary
0  101  Mithun   25       dev   25000
1  102   Dipin   26  sreenath   34000
2  103    jose   27   sreerag   37000

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',suffixes=['_left','_right'])

    id name_left  age name_right  salary
0  101    Mithun   25        dev   25000
1  102     Dipin   26   sreenath   34000
2  103      jose   27    sreerag   37000

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='outer')

    id   name_x   age    name_y   salary
0  101   Mithun  25.0       dev  25000.0
1  102    Dipin  26.0  sreenath  34000.0
2  103     jose  27.0   sreerag  37000.0
3  105      NaN   NaN     varun  20000.0
4  106  maneesh  29.0       NaN      NaN

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='outer',indicator=True)

    id   name_x   age    name_y   salary      _merge
0  101   Mithun  25.0       dev  25000.0        both
1  102    Dipin  26.0  sreenath  34000.0        both
2  103     jose  27.0   sreerag  37000.0        both
3  105      NaN   NaN     varun  20000.0  right_only
4  106  maneesh  29.0       NaN      NaN   left_only

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how='left')

    id   name_x  age    name_y   salary
0  101   Mithun   25       dev  25000.0
1  102    Dipin   26  sreenath  34000.0
2  103     jose   27   sreerag  37000.0
3  106  maneesh   29       NaN      NaN

In [ ]:
pd.merge(tcs_emp,wipro_emp,on='id',how="right")

    id  name_x   age    name_y  salary
0  101  Mithun  25.0       dev   25000
1  102   Dipin  26.0  sreenath   34000
2  103    jose  27.0   sreerag   37000
3  105     NaN   NaN     varun   20000

# Pivot an Pivot Tables

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/weather.csv")
df

         date       city  temperature  humidity
0  2024-01-01     Mumbai           16        90
1  2024-01-02     Mumbai           16        60
2  2024-01-03    Kolkata           25        51
3  2024-01-04     Mumbai           23        94
4  2024-01-05    Chennai           38        50
5  2024-01-06  Hyderabad           43        60
6  2024-01-07      Delhi           32        42
7  2024-01-08     Mumbai           45        95
8  2024-01-09  Bangalore           26        92
9  2024-01-10    Kolkata           22        94

In [ ]:
df.set_index('date',inplace=True)

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/weather_500_rows_repeating_dates.csv")
df

           date       city  temperature  humidity
0    2024-01-13  Hyderabad           40        77
1    2024-02-13    Kolkata           21        69
2    2024-02-11      Delhi           23        36
3    2024-01-23  Hyderabad           27        75
4    2024-02-19  Bangalore           31        82
..          ...        ...          ...       ...
495  2024-01-12    Chennai           16        70
496  2024-01-18  Bangalore           31        37
497  2024-01-21     Mumbai           17        45
498  2024-01-09     Mumbai           17        68
499  2024-02-02  Hyderabad           38        83

[500 rows x 4 columns]

In [ ]:
df.pivot_table(index='city',columns='date')

            humidity                                                         \
date      2024-01-01 2024-01-02 2024-01-03 2024-01-04 2024-01-05 2024-01-06
city
Bangalore  67.666667      67.50  63.333333  82.000000        NaN       71.0
Chennai    74.000000        NaN  52.666667  91.000000       84.0       80.0
Delhi      86.000000      39.00  89.000000  70.333333       71.0       63.0
Hyderabad        NaN      52.25  43.000000  54.000000       53.0       60.5
Kolkata    47.000000      56.00  87.500000        NaN       71.0       63.0
Mumbai           NaN      48.00        NaN  37.000000       76.0       41.5

                                                       ... temperature  \
date      2024-01-07 2024-01-08 2024-01-09 2024-01-10  ...  2024-02-10
city                                                   ...
Bangalore  70.333333       61.0      76.00        NaN  ...        28.0
Chennai    82.000000        NaN      37.00      83.75  ...        32.5
Delhi      62.333333       62.0      58.00      40.00  ...        28.0
Hyderabad  79.000000       58.5      78.25      58.00  ...        15.0
Kolkata          NaN       64.0        NaN      69.80  ...         NaN
Mumbai     72.750000       40.0      71.50      47.00  ...         NaN

                                                                             \
date      2024-02-11 2024-02-12 2024-02-13 2024-02-14 2024-02-15 2024-02-16
city
Bangalore       24.0  34.000000       16.0       29.0        NaN       32.5
Chennai          NaN  33.333333       16.0       30.0  22.333333       43.0
Delhi           24.0  33.000000       41.0       39.5  20.000000       18.0
Hyderabad       15.0  35.000000       32.0       17.0        NaN       26.5
Kolkata         26.5        NaN       26.0       27.0  28.500000       33.0
Mumbai          33.0  38.000000       27.0        NaN  27.000000       31.5


date      2024-02-17 2024-02-18 2024-02-19
city
Bangalore  33.666667       19.0  29.666667
Chennai    24.800000       19.5  29.333333
Delhi            NaN       40.0  21.000000
Hyderabad  18.000000       19.0  35.333333
Kolkata    31.000000       32.0  19.000000
Mumbai     26.500000       30.5  31.000000

[6 rows x 100 columns]

In [ ]:
df.pivot(columns='city')

            date                                                              \
city   Bangalore     Chennai       Delhi   Hyderabad     Kolkata      Mumbai
0            NaN         NaN         NaN  2024-01-13         NaN         NaN
1            NaN         NaN         NaN         NaN  2024-02-13         NaN
2            NaN         NaN  2024-02-11         NaN         NaN         NaN
3            NaN         NaN         NaN  2024-01-23         NaN         NaN
4     2024-02-19         NaN         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
495          NaN  2024-01-12         NaN         NaN         NaN         NaN
496   2024-01-18         NaN         NaN         NaN         NaN         NaN
497          NaN         NaN         NaN         NaN         NaN  2024-01-21
498          NaN         NaN         NaN         NaN         NaN  2024-01-09
499          NaN         NaN         NaN  2024-02-02         NaN         NaN

     temperature                                         humidity          \
city   Bangalore Chennai Delhi Hyderabad Kolkata Mumbai Bangalore Chennai
0            NaN     NaN   NaN      40.0     NaN    NaN       NaN     NaN
1            NaN     NaN   NaN       NaN    21.0    NaN       NaN     NaN
2            NaN     NaN  23.0       NaN     NaN    NaN       NaN     NaN
3            NaN     NaN   NaN      27.0     NaN    NaN       NaN     NaN
4           31.0     NaN   NaN       NaN     NaN    NaN      82.0     NaN
..           ...     ...   ...       ...     ...    ...       ...     ...
495          NaN    16.0   NaN       NaN     NaN    NaN       NaN    70.0
496         31.0     NaN   NaN       NaN     NaN    NaN      37.0     NaN
497          NaN     NaN   NaN       NaN     NaN   17.0       NaN     NaN
498          NaN     NaN   NaN       NaN     NaN   17.0       NaN     NaN
499          NaN     NaN   NaN      38.0     NaN    NaN       NaN     NaN


city Delhi Hyderabad Kolkata Mumbai
0      NaN      77.0     NaN    NaN
1      NaN       NaN    69.0    NaN
2     36.0       NaN     NaN    NaN
3      NaN      75.0     NaN    NaN
4      NaN       NaN     NaN    NaN
..     ...       ...     ...    ...
495    NaN       NaN     NaN    NaN
496    NaN       NaN     NaN    NaN
497    NaN       NaN     NaN   45.0
498    NaN       NaN     NaN   68.0
499    NaN      83.0     NaN    NaN

[500 rows x 18 columns]

In [ ]:
df.pivot(columns='city',values='temperature')

city  Bangalore  Chennai  Delhi  Hyderabad  Kolkata  Mumbai
0           NaN      NaN    NaN       40.0      NaN     NaN
1           NaN      NaN    NaN        NaN     21.0     NaN
2           NaN      NaN   23.0        NaN      NaN     NaN
3           NaN      NaN    NaN       27.0      NaN     NaN
4          31.0      NaN    NaN        NaN      NaN     NaN
..          ...      ...    ...        ...      ...     ...
495         NaN     16.0    NaN        NaN      NaN     NaN
496        31.0      NaN    NaN        NaN      NaN     NaN
497         NaN      NaN    NaN        NaN      NaN    17.0
498         NaN      NaN    NaN        NaN      NaN    17.0
499         NaN      NaN    NaN       38.0      NaN     NaN

[500 rows x 6 columns]

## Pivot Grouper

In [ ]:
import pandas as pd
# Load dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/Sales_data (1).csv",parse_dates=["Date"])
df

   OrderID       Date     Category     Product  Quantity  Price
0     1001 2023-01-15  Electronics      Laptop         2  70000
1     1002 2023-01-20    Furniture       Chair         4   1500
2     1003 2023-02-05  Electronics  Headphones         5   2000
3     1004 2023-02-18    Furniture       Table         1   5000
4     1005 2023-03-03   Stationery    Notebook        10     50
5     1006 2023-03-25  Electronics       Mouse         6    800
6     1007 2023-04-10    Furniture        Sofa         1  15000
7     1008 2023-04-15   Stationery         Pen        20     20
8     1009 2023-05-01  Electronics      Laptop         1  70000
9     1010 2023-05-12    Furniture       Chair         2   1500

In [ ]:
# Add total sales column
df["Total"]=df["Quantity"]*df["Price"]
df

   OrderID       Date     Category     Product  Quantity  Price   Total
0     1001 2023-01-15  Electronics      Laptop         2  70000  140000
1     1002 2023-01-20    Furniture       Chair         4   1500    6000
2     1003 2023-02-05  Electronics  Headphones         5   2000   10000
3     1004 2023-02-18    Furniture       Table         1   5000    5000
4     1005 2023-03-03   Stationery    Notebook        10     50     500
5     1006 2023-03-25  Electronics       Mouse         6    800    4800
6     1007 2023-04-10    Furniture        Sofa         1  15000   15000
7     1008 2023-04-15   Stationery         Pen        20     20     400
8     1009 2023-05-01  Electronics      Laptop         1  70000   70000
9     1010 2023-05-12    Furniture       Chair         2   1500    3000

In [ ]:
# create pivot table with Grouper(montly)
pivot = pd.pivot_table(
    df,
    index=pd.Grouper(key='Date', freq='M'),
    columns='Category',
    values='Total',
    aggfunc='sum'
)

pivot

/tmp/ipython-input-4220857531.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  index=pd.Grouper(key='Date', freq='M'),

Category    Electronics  Furniture  Stationery
Date
2023-01-31     140000.0     6000.0         NaN
2023-02-28      10000.0     5000.0         NaN
2023-03-31       4800.0        NaN       500.0
2023-04-30          NaN    15000.0       400.0
2023-05-31      70000.0     3000.0         NaN

## Melt
- Melt allows to transform or reshape the data

In [ ]:
import pandas as pd
datas =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/weather_dataset (4).csv")
datas

,Date,City,Temperature,Humidity,Wind Speed (km/h),Weather Condition
0,2025-08-01,Mumbai,30,85,12,Rainy
1,2025-08-01,Delhi,36,40,18,Sunny
2,2025-08-01,Bengaluru,27,70,10,Cloudy
3,2025-08-02,Mumbai,29,88,14,Rainy
4,2025-08-02,Delhi,35,45,20,Sunny
5,2025-08-02,Bengaluru,26,72,9,Cloudy
6,2025-08-03,Mumbai,28,90,11,Rainy
7,2025-08-03,Delhi,34,50,22,Partly Cloudy
8,2025-08-03,Bengaluru,27,68,8,Cloudy

In [ ]:
pd.melt(datas,id_vars=["Date"])

          Date           variable          value
0   2025-08-01               City         Mumbai
1   2025-08-01               City          Delhi
2   2025-08-01               City      Bengaluru
3   2025-08-02               City         Mumbai
4   2025-08-02               City          Delhi
5   2025-08-02               City      Bengaluru
6   2025-08-03               City         Mumbai
7   2025-08-03               City          Delhi
8   2025-08-03               City      Bengaluru
9   2025-08-01        Temperature             30
10  2025-08-01        Temperature             36
11  2025-08-01        Temperature             27
12  2025-08-02        Temperature             29
13  2025-08-02        Temperature             35
14  2025-08-02        Temperature             26
15  2025-08-03        Temperature             28
16  2025-08-03        Temperature             34
17  2025-08-03        Temperature             27
18  2025-08-01           Humidity             85
19  2025-08-01           Humidity             40
20  2025-08-01           Humidity             70
21  2025-08-02           Humidity             88
22  2025-08-02           Humidity             45
23  2025-08-02           Humidity             72
24  2025-08-03           Humidity             90
25  2025-08-03           Humidity             50
26  2025-08-03           Humidity             68
27  2025-08-01  Wind Speed (km/h)             12
28  2025-08-01  Wind Speed (km/h)             18
29  2025-08-01  Wind Speed (km/h)             10
30  2025-08-02  Wind Speed (km/h)             14
31  2025-08-02  Wind Speed (km/h)             20
32  2025-08-02  Wind Speed (km/h)              9
33  2025-08-03  Wind Speed (km/h)             11
34  2025-08-03  Wind Speed (km/h)             22
35  2025-08-03  Wind Speed (km/h)              8
36  2025-08-01  Weather Condition          Rainy
37  2025-08-01  Weather Condition          Sunny
38  2025-08-01  Weather Condition         Cloudy
39  2025-08-02  Weather Condition          Rainy
40  2025-08-02  Weather Condition          Sunny
41  2025-08-02  Weather Condition         Cloudy
42  2025-08-03  Weather Condition          Rainy
43  2025-08-03  Weather Condition  Partly Cloudy
44  2025-08-03  Weather Condition         Cloudy

In [ ]:
melted = pd.melt(
    datas,
    id_vars=["City","Date",'Weather Condition'],
    value_vars=['Temperature', 'Humidity'],
    var_name='Weather_Parameter',
    value_name='Reading'
)
melted

         City        Date Weather Condition Weather_Parameter  Reading
0      Mumbai  2025-08-01             Rainy       Temperature       30
1       Delhi  2025-08-01             Sunny       Temperature       36
2   Bengaluru  2025-08-01            Cloudy       Temperature       27
3      Mumbai  2025-08-02             Rainy       Temperature       29
4       Delhi  2025-08-02             Sunny       Temperature       35
5   Bengaluru  2025-08-02            Cloudy       Temperature       26
6      Mumbai  2025-08-03             Rainy       Temperature       28
7       Delhi  2025-08-03     Partly Cloudy       Temperature       34
8   Bengaluru  2025-08-03            Cloudy       Temperature       27
9      Mumbai  2025-08-01             Rainy          Humidity       85
10      Delhi  2025-08-01             Sunny          Humidity       40
11  Bengaluru  2025-08-01            Cloudy          Humidity       70
12     Mumbai  2025-08-02             Rainy          Humidity       88
13      Delhi  2025-08-02             Sunny          Humidity       45
14  Bengaluru  2025-08-02            Cloudy          Humidity       72
15     Mumbai  2025-08-03             Rainy          Humidity       90
16      Delhi  2025-08-03     Partly Cloudy          Humidity       50
17  Bengaluru  2025-08-03            Cloudy          Humidity       68

## Cross tab or contigency table
- In pandas,pd.crosstab() is used to compute a cross-tabulation of two or more factors. It’s often used for analyzing categorical variables, similar to a contingency table in statistics.

syntax:

pd.crosstab(index, columns, values=None, aggfunc=None, margins=False, margins_name='All')

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/survey_crosstab (1).csv")
df

   RespondentID  Gender AgeGroup Preferred_Device
0             1    Male    18-25           Laptop
1             2  Female    26-35           Mobile
2             3    Male    18-25           Tablet
3             4  Female    18-25           Mobile
4             5    Male    26-35           Laptop
5             6  Female    18-25           Mobile
6             7    Male    36-45           Laptop
7             8  Female    26-35           Tablet
8             9    Male    26-35           Mobile
9            10  Female    36-45           Laptop

In [ ]:
# Create cross-tabulation
ct = pd.crosstab(df['Gender'], df['Preferred_Device'])

print(ct)

Preferred_Device  Laptop  Mobile  Tablet
Gender
Female                 1       3       1
Male                   3       1       1

In [ ]:
# Cross-tab of AgeGroup vs Preferred_Device with totals:

ct2 = pd.crosstab(df['AgeGroup'], df['Preferred_Device'], margins=True, margins_name='Total')
print(ct2)

Preferred_Device  Laptop  Mobile  Tablet  Total
AgeGroup
18-25                  1       2       1      4
26-35                  1       2       1      4
36-45                  2       0       0      2
Total                  4       4       2     10